#!/usr/bin/env python3
"""
Export FreqMLP float32 weights to mlp_weights.h for x86.
"""
import sys
import numpy as np
import torch
import joblib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from model import FreqMLP

TRAINING_DIR = Path(__file__).parent
DATA_DIR     = TRAINING_DIR.parent

# Must match train.py
INPUT_DIM  = 330
N_CLASSES  = 12
LAYER_DIMS = [512, 256, 128, 64, N_CLASSES]

DVFS_STEPS = [
    400000, 800000, 1200000, 1600000, 2000000, 2400000, 
    2800000, 3200000, 3600000, 4000000, 4400000, 4800000
]

# Indices of Linear layers inside model.net Sequential
LINEAR_INDICES = [0, 3, 6, 9, 11]

def emit_1d(name, arr, vals_per_line=8):
    flat = arr.astype(np.float32).ravel()
    n    = flat.size
    lines = [f'static const float {name}[{n}] = {{']
    for i in range(0, n, vals_per_line):
        chunk = flat[i : i + vals_per_line]
        lines.append('    ' + ', '.join(f'{v:.8e}f' for v in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    model_path = TRAINING_DIR / 'model_fp32.pt'
    if not model_path.exists():
        print(f"Error: {model_path} not found. Run train.py first.")
        return

    model = FreqMLP(input_dim=INPUT_DIM, num_classes=N_CLASSES)
    model.load_state_dict(
        torch.load(model_path, map_location='cpu', weights_only=True)
    )
    model.eval()

    scaler_path = TRAINING_DIR / 'scaler.pkl'
    if not scaler_path.exists():
        print(f"Error: {scaler_path} not found. Run train.py first.")
        return
    scaler = joblib.load(scaler_path)

    W = []
    b = []
    for idx in LINEAR_INDICES:
        layer = model.net[idx]
        W.append(layer.weight.detach().numpy().copy())
        b.append(layer.bias.detach().numpy().copy())

    # Fold StandardScaler into layer 1
    W[0] = W[0] / scaler.scale_
    b[0] = b[0] - W[0] @ scaler.mean_

    # Sanity-check shapes
    expected_shapes = [
        (LAYER_DIMS[0], INPUT_DIM),
        (LAYER_DIMS[1], LAYER_DIMS[0]),
        (LAYER_DIMS[2], LAYER_DIMS[1]),
        (LAYER_DIMS[3], LAYER_DIMS[2]),
        (LAYER_DIMS[4], LAYER_DIMS[3]),
    ]
    for i, (w, expected) in enumerate(zip(W, expected_shapes)):
        assert w.shape == expected, f'L{i+1} weight shape {w.shape} != {expected}'

    # ── emit header ───────────────────────────────────────────────────────────

    h = []
    h.append('/* Auto-generated by export_weights.py — do not edit. */')
    h.append(f'/* FreqMLP: {INPUT_DIM} → 512 → 256 → 128 → 64 → {N_CLASSES} */')
    h.append('')
    h.append('#ifndef MLP_WEIGHTS_H')
    h.append('#define MLP_WEIGHTS_H')
    h.append('')
    h.append(f'#define MLP_INPUT_DIM   {INPUT_DIM}')
    h.append(f'#define MLP_L1_OUT      {LAYER_DIMS[0]}')
    h.append(f'#define MLP_L2_OUT      {LAYER_DIMS[1]}')
    h.append(f'#define MLP_L3_OUT      {LAYER_DIMS[2]}')
    h.append(f'#define MLP_L4_OUT      {LAYER_DIMS[3]}')
    h.append(f'#define MLP_N_CLASSES   {N_CLASSES}')
    h.append('')

    h.append('static const unsigned int mlp_dvfs_steps[MLP_N_CLASSES] = {')
    h.append('    ' + ', '.join(str(s) for s in DVFS_STEPS))
    h.append('};')
    h.append('')

    for i, (w, bias) in enumerate(zip(W, b), start=1):
        rows, cols = w.shape
        h.append(f'/* Layer {i}: ({rows} x {cols}) */')
        h.append(emit_1d(f'mlp_w{i}', w))
        h.append('')
        h.append(emit_1d(f'mlp_b{i}', bias))
        h.append('')

    h.append('#endif /* MLP_WEIGHTS_H */')
    h.append('')

    out_path = TRAINING_DIR / 'mlp_weights.h'
    out_path.write_text('\n'.join(h))
    print(f'wrote {out_path}')

if __name__ == '__main__':
    main()
