#!/usr/bin/env python3
"""
Export FreqMLP float32 weights to mlp_weights.h for kernel deployment.

Folds the StandardScaler into layer 1 so the kernel receives raw features
with no separate normalization step.

Usage:
    cd src/training
    python3 export_weights.py

Output: mlp_weights.h  (move next to your kernel module .c file before building)
"""
import sys
import numpy as np
import torch
import joblib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from model import FreqMLP

TRAINING_DIR = Path(__file__).parent
DATA_DIR     = TRAINING_DIR.parent / 'data_collection'

# Must match train.py
INPUT_DIM  = 174
N_CLASSES  = 22
LAYER_DIMS = [256, 128, 64, N_CLASSES]   # output dims of each Linear layer

DVFS_STEPS = [
    115200,  192000,  268800,  345600,  422400,  499200,
    576000,  652800,  729600,  806400,  883200,  960000,
    1036800, 1113600, 1190400, 1267200, 1344000, 1420800,
    1497600, 1574400, 1651200, 1728000,
]

# Indices of Linear layers inside model.net Sequential
LINEAR_INDICES = [0, 3, 6, 8]


def emit_1d(name, arr, vals_per_line=8):
    """Emit a flat C array initializer for a numpy array of any shape."""
    flat = arr.astype(np.float32).ravel()
    n    = flat.size
    lines = [f'static const float {name}[{n}] = {{']
    for i in range(0, n, vals_per_line):
        chunk = flat[i : i + vals_per_line]
        lines.append('    ' + ', '.join(f'{v:.8e}f' for v in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    model = FreqMLP(input_dim=INPUT_DIM, num_classes=N_CLASSES)
    model.load_state_dict(
        torch.load(TRAINING_DIR / 'model_fp32.pt', map_location='cpu', weights_only=True)
    )
    model.eval()

    scaler = joblib.load(TRAINING_DIR / 'scaler.pkl')

    # Extract weights from each Linear layer
    W = []
    b = []
    for idx in LINEAR_INDICES:
        layer = model.net[idx]
        W.append(layer.weight.detach().numpy().copy())   # (out, in)
        b.append(layer.bias.detach().numpy().copy())     # (out,)

    # Fold StandardScaler into layer 1.
    #   scaler:  x_norm = (x - mean) / std
    #   linear:  y = W @ x_norm + b
    #          = (W / std) @ x + (b - W/std @ mean)
    W[0] = W[0] / scaler.scale_          # broadcast: divide each column j by scale[j]
    b[0] = b[0] - W[0] @ scaler.mean_

    # Sanity-check shapes
    expected_shapes = [
        (LAYER_DIMS[0], INPUT_DIM),
        (LAYER_DIMS[1], LAYER_DIMS[0]),
        (LAYER_DIMS[2], LAYER_DIMS[1]),
        (LAYER_DIMS[3], LAYER_DIMS[2]),
    ]
    for i, (w, expected) in enumerate(zip(W, expected_shapes)):
        assert w.shape == expected, f'L{i+1} weight shape {w.shape} != {expected}'

    feature_cols = (DATA_DIR / 'feature_cols.txt').read_text().strip().split('\n')
    assert len(feature_cols) == INPUT_DIM // 2, (
        f'Expected {INPUT_DIM // 2} feature cols, got {len(feature_cols)}'
    )

    # ── emit header ───────────────────────────────────────────────────────────

    h = []

    h.append('/* Auto-generated by export_weights.py — do not edit. */')
    h.append('/* FreqMLP: 174 → 256 → 128 → 64 → 22               */')
    h.append('/* StandardScaler folded into layer 1 weights.        */')
    h.append('')
    h.append('#ifndef MLP_WEIGHTS_H')
    h.append('#define MLP_WEIGHTS_H')
    h.append('')
    h.append(f'#define MLP_INPUT_DIM   {INPUT_DIM}')
    h.append(f'#define MLP_L1_OUT      {LAYER_DIMS[0]}')
    h.append(f'#define MLP_L2_OUT      {LAYER_DIMS[1]}')
    h.append(f'#define MLP_L3_OUT      {LAYER_DIMS[2]}')
    h.append(f'#define MLP_N_CLASSES   {N_CLASSES}')
    h.append('')

    # DVFS step table
    h.append('/* DVFS frequency steps (kHz) indexed by model output class */')
    h.append('static const unsigned int mlp_dvfs_steps[MLP_N_CLASSES] = {')
    h.append('    ' + ', '.join(str(s) for s in DVFS_STEPS))
    h.append('};')
    h.append('')

    # Feature index reference comment
    h.append('/*')
    h.append(' * Input layout: indices [0, 86] are the current snapshot,')
    h.append(' *               indices [87, 173] are the per-step deltas.')
    h.append(' * Feature order within each half:')
    for i, col in enumerate(feature_cols):
        h.append(f' *   [{i:2d} / {i + INPUT_DIM // 2:3d}]  {col}')
    h.append(' */')
    h.append('')

    # Weights and biases, one layer at a time
    for i, (w, bias) in enumerate(zip(W, b), start=1):
        rows, cols = w.shape
        h.append(f'/* Layer {i}: ({rows} x {cols}), stored row-major */')
        h.append(f'/* Access: mlp_w{i}[out_idx * {cols} + in_idx]    */')
        h.append(emit_1d(f'mlp_w{i}', w))
        h.append('')
        h.append(emit_1d(f'mlp_b{i}', bias))
        h.append('')

    h.append('#endif /* MLP_WEIGHTS_H */')
    h.append('')

    out_path = TRAINING_DIR / 'mlp_weights.h'
    out_path.write_text('\n'.join(h))

    # ── summary ───────────────────────────────────────────────────────────────

    total = sum(w.size + bias.size for w, bias in zip(W, b))
    print(f'wrote {out_path}  ({out_path.stat().st_size / 1024:.0f} KB source)')
    print(f'{total:,} float32 parameters  ({total * 4 / 1024:.1f} KB binary)')
    for i, (w, bias) in enumerate(zip(W, b), start=1):
        print(f'  L{i}  weight {w.shape}  bias ({bias.size},)')


if __name__ == '__main__':
    main()
